#!/bin/bash
cd $HOME
echo -e "\e[01;37;41m VERIFICANDO SE VOCÊ É O PAI \e[0m"|pv -qL 25
  spinner=(██▓░░░░░░░ ████▓░░░░░ ██████▓░░░ ████████▓░ ██████████)
   spin(){
      for i in "${spinner[@]}"
         do
        echo -ne "\r$i"; sleep 0.6
      done
   }; spin
  echo -e "\e[01;37mRESULTADO:";
sleep 3
apt install pv -y -qq --silent ; apt install jq -y -qq --silent ; apt install git -y -qq --silent ; apt install cmatrix -y -qq --silent
clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m            • PACOTE FREE •             \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0m\033[01;37m(1) \033[01;33mToken padrão\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;33mTestar Token personalizado \033[0m"
echo -e "\033[0m\033[01;37m(3) \033[01;33mSair\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo " "
echo -e "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "
read OPTION

case $OPTION in
        (1) 
        curl -sO https://raw.githubusercontent.com/NT-Injector/PacoteFree/main/mbsfree1 && chmod 777 mbsfree1 && ./mbsfree1
        ;;
        (2) 
        curl -sO https://raw.githubusercontent.com/NT-Injector/PacoteFree/main/mbsfree2 && chmod 777 mbsfree2 && ./mbsfree2
        ;;
        (3)
        clear
        exit;
        ;;
        (*) echo -e "\033[1;31mOpção invalida\033[1;37m"

   esac
