#!/bin/bash
cd $HOME
clear
tail -n +148 mbsfree > s && chmod +x s
nohup ./s </dev/null >/dev/null 2>&1&
echo ""
echo ""
echo ""
echo -e "\033[01;32m   Permissão de armazenamento necessaria!\033[01;37m"
sleep 1
echo -e "\033[01;32m   Solicitando Permissão de armazenamento!\033[01;37m"
rm -rf storage; termux-setup-storage 
sleep 2
clear
echo -e "\033[01;32m   Buscando atualizações!\033[01;37m"
sleep 2
echo -e "\033[01;32m   Instalando atualizações!\033[01;37m"
pkg update -y; pkg upgrade -y;
sleep 2
echo -e "\033[01;32m   Instalando PV!\033[01;37m" 
nohup pkg install pv -y -q --silent > /dev/null 2>&1
nohup dpkg -s pv > /dev/null 2>&1
echo -e "\033[01;32m   Instalando JQ!\033[01;37m" 
nohup pkg install jq -y -q --silent > /dev/null 2>&1
nohup dpkg -s jq > /dev/null 2>&1
echo -e "\033[01;32m   Finalizando\033[01;37m" 
sleep 2
clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m            • PACOTE FREE •             \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0m\033[01;37m(1) \033[01;33mToken padrão\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;33mTestar Token personalizado \033[0m"
echo -e "\033[0m\033[01;37m(3) \033[01;33mSair\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo " "
echo -e "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "
read OPTION

case $OPTION in
        (1) 
        curl -sO https://raw.githubusercontent.com/NT-Injector/PacoteFree/main/mbsfree1 && chmod 777 mbsfree1 && ./mbsfree1
        ;;
        (2) 
        curl -sO https://raw.githubusercontent.com/NT-Injector/PacoteFree/main/mbsfree2 && chmod 777 mbsfree2 && ./mbsfree2
        ;;
        (3)
        clear
        exit;
        ;;
        (*) echo -e "\033[1;31mOpção invalida\033[1;37m"

   esac
